### ISSUE TITLE
Implement Product Gallery component for Venia

### ISSUE THREAD

**Issue by ericerway** [magento/pwa-studio#163]
## This issue is for the following packages:

[X] `venia-concept`
[ ] `pwa-buildpack`
[ ] `peregrine`
[ ] `pwa-module`
[ ] `pwa-devdocs`

**As a shopper, I want to browse an image gallery (carousel) in multiple contexts such as related products or recommended so that I can make a purchase**

## Description

https://magento-research.github.io/pwa-studio/venia-pwa-concept/component/image-carousel/

![image.png](https://images.zenhubusercontent.com/5a71f21a4b5806bc2bc51012/6f770bdd-be6a-4adb-aa9e-46968ed56776)

![image.png](https://images.zenhubusercontent.com/5a71f21a4b5806bc2bc51012/561b3ef0-0159-451f-aec7-dea53c9e37af)

As a developer I want to create a product gallery component for Venia so that I can display rich content by criteria from the Magento CMS.

- Examples include Recommended For You carousel from https://magento-research.github.io/pwa-studio/venia-pwa-concept/design/homepage/
- Primary product image is independent from gallery (secondary) images
- See All Recommended and Ratings will be part of future iteration
- Coverflow not in scope for MVP; desirable stretch goal

#### Assumptions
- Successful setup and completion of Venia examples
- Sample data (mock data in JSON; not GraphQL dependent); 
- Well formatted and proper content (data); mobile first and UX principles established in design documentation.

## Tasks

- [ ] Implement basic shell component with GraphQL query for New Arrivals
- [ ] Decide and implement animation strategy for scrolling
- [ ] Implement on demand data fetching to avoid downloads of content never seen

**Comment by awilcoxa** [comment]
closing this story for now as we have additional (newer) stories to represent effort for implementing recommended/similar products.
