### ISSUE TITLE
Release Checklist 4.0.0 - GA

### ISSUE THREAD

**Issue by cherdman** [magento/pwa-studio#1695]
### GA
- [x]   Merge release 4.0.0 to master with new release tag and pre-release in github (Automated )
- [x]   Publish to NPM/package managers (Automated )
- [x]   Copy CHANGELOG to Github release details @dpatil-magento 
- [x]   Publish devdocs  @jcalcaben 
- [x]   Release  upward-php @dpatil-magento 
- [x]   Release upward-connector @dpatil-magento 
- [x]   Deploy latest on Cloud Pro Staging env @dpatil-magento 
- [x]   Deploy latest on Cloud Pro Production env @dpatil-magento 
- [x]   Verify AWS instance is auto deployed (Automated )
- [x]   merge master to develop @jcalcaben - Can you help in this?   Tracked via https://github.com/magento/pwa-studio/issues/1863

**Comment by cherdman** [comment]
Let's GA on Monday, October 7.

**Comment by dpatil-magento** [comment]
All listed tasks complete, closing this one.
