### ISSUE TITLE
Release Checklist 4.0.0 - RTM

### ISSUE THREAD

**Issue by cherdman** [magento/pwa-studio#1696]
### RTM
- [x] Author & Merge Release Notes to ./changelog.md  @jcalcaben 
- [x] Commit Release Notes @jcalcaben 
- [x] Approve/signoff build @dpatil-magento 
- [x] Tag `rc-1` to packages and publish packages to NPM  @dpatil-magento 
- [x] Verify AWS deploy & scale configuration @dpatil-magento 
- [x] Deploy to Magento Cloud Pro Staging  @dpatil-magento

**Comment by dpatil-magento** [comment]
QA sign-off on 53a1c009b5c8e8eccc3d8afe67a1547726829400

**Comment by dpatil-magento** [comment]
All checks complete.
