### ISSUE TITLE
[feature]:  account recovery for Venia (MVP)

### ISSUE THREAD

**Issue by ericerway** [magento/pwa-studio#251]
## This issue is for the following packages:

[X] `venia-concept`
[ ] `pwa-buildpack`
[ ] `peregrine`
[ ] `pwa-module`
[ ] `pwa-devdocs`

## Description

Email recovery was delivered in #253 this story represents the effort to ensure that account recovery is now using Venia/Peregrine frameworks and to account for a minor text update needed. 

## Tasks
- [ ] Account Recovery functional component refactor
- [ ] GraphQL refactor
- [ ] Update email form field text per @soumya-ashok mockup
- [ ] Testing and documentation (as appropriate)

**Comment by ericerway** [comment]
Future considerations for "magic link" and separate link to reset password (itself)

**Comment by ericerway** [comment]
Kamino cloned this issue to [magento-research/pwa-studio](https://github.com/magento-research/pwa-studio/issues/253)

**Comment by awilcoxa** [comment]
Already delivered as a part of #253, repurposing issue to represent text change required per @soumya-ashok

**Comment by awilcoxa** [comment]
Needs evaluation to determine if GQL is being used and if the proper back end integration for email is completed

**Comment by cherdman** [comment]
https://jira.corp.magento.com/browse/PWA-77

**Comment by sirugh** [comment]
Done in linked ticket, PWA-77
