### ISSUE TITLE
Release 12.0.0 Checklist

### ISSUE THREAD

**Issue by supernova-at** [magento/pwa-studio#3466]
# PWA Studio Release Process

This document details the process to perform a release of PWA Studio.

There are two "stages" of release: Release to Marketing or "RTM", and General Availability or "GA".

## Release to Marketing

The Release to Marketing (RTM) release is the initial release candidate.

### RTM Checklist

- [x] Cut a new git branch based from `develop` named `release/12.0.0`
- [x] Inform docs that they can begin authoring the Release Notes
- [x] Set the "Fix Version" of all tickets in the "Ready for Release" column to "PWA-12.0.0"
- [x] Update `magento-compatibility.js`
  - Note: PWA Studio releases must be compatible with the most recent version of the Magento backend
- [x] Merge the Release Notes into `release/12.0.0`
- [x] Merge `magento-compatibility.js` into `release/12.0.0`
- [x] Have QA approve and sign off on the build
- [x] Tag `rc-1` to packages and publish packages to NPM
  - Note: This is an automated process. See internal "PWA release automation" wiki page
- [x] Verify the automated AWS deploy and scale configuration were created successfully
- [x] Deploy to Magento Cloud Staging
- [x] QA has approved the RTM release

### GA Checklist

The General Availability (GA) release is the final release candidate.

- [x] Merge `release/12.0.0` branch to `master`
- [x] Perform pre-release in GitHub (Automated)
- [x] Publish to NPM
  - Note: This is an automated process. See internal "PWA release automation" wiki page
- [x] Copy and paste the [CHANGELOG.md](https://github.com/magento/pwa-studio/blob/release/12.0.0/CHANGELOG.md) into the GitHub release details field
- [x] Publish the Dev Docs
- [x] Release `upward-php`
- [x] Release `upward-connector`
- [x] Verify the AWS instance was correctly deployed to https://magento.pwa-venia.com/
- [x] Add new home page data to backend
- [x] Deploy latest on `mcstaging` Cloud Pro environment
- [x] Deploy latest on `production` Cloud Pro environment
- [x] Merge `master` to `develop`
- [x] Release MFTF tests

## Post-Release Cleanup

- [x] Identify JIRA tickets in "Ready for Release" that were included in this release
- [x] Ensure the "Fix Version" for these tickets is set to `PWA-12.0.0`
- [x] Bulk edit these tickets and move them to "Done"
  - [x] Select a resolution of "Fixed" and add a comment: "Released in version 12.0.0."
- [x] Go to "Releases" in JIRA, find "PWA-12.0.0" and click `Actions` > `Release`
