### ISSUE TITLE
Implement Order Details for Venia (PWA)

### ISSUE THREAD

**Issue by ericerway** [magento/pwa-studio#350]
## This issue is for the following packages:

[X] `venia-concept`
[ ] `pwa-buildpack`
[X] `peregrine`
[ ] `pwa-module`
[ ] `pwa-devdocs`

## Description

https://magento.invisionapp.com/d/main#/console/14921712/324119966/preview

![image](https://user-images.githubusercontent.com/2686596/46779960-76c0f100-cd1a-11e8-966e-d0181b6c03fe.png)

![image](https://user-images.githubusercontent.com/2686596/46780111-4d549500-cd1b-11e8-9cf2-1fa340cebc20.png)

As a shopper, I want to view details from an order placed on Venia so that I can buy again, share or review item in the future. 

- All products associated with order (ID#)
- Product details with each item (name, details, quantity, unit price)
- Actions associated by item (buy again, share item)
- Details of order (number, date, total and # products)

#### Assumptions
- Dependent on Purchase History experience (complete)
- Reviews will be considered in the future; Ratings API needed
- Track Order will be considered in the future
- Buy again will be targeted at the item level not order (B2B in future)
 
## Tasks
- [ ] Implement Order Details and Order Summary (unauthenticated)
- [ ] Implement order/item groupings (items in this order)
- [ ] Implement item actions (buy again, share)
- [ ] Implement shipment and payment details
- [ ] Discovery for Order Details via Purchase History (authenticated)
- [ ] Testing and documentation (https://github.com/magento-research/pwa-studio/wiki/Documentation-Guidelines)

**Comment by ericerway** [comment]
Kamino cloned this issue to [magento-research/pwa-studio](https://github.com/magento-research/pwa-studio/issues/351)

**Comment by ericerway** [comment]
Related to #294 - candidate for next sprint.

**Comment by Starotitorov** [comment]
@ericerway, We will not be able to estimate this story for now. According to requirements we need to fetch order details and order summary for guest users, but right now Magento allows to retrieve information about order only for authorized users. I have already discussed this question with @zetlen previously and he confirmed this fact.

Right now we can implement only static markup and styling for the story.
Frontend tasks:
1. Implement common button group component 1SP.
2. Implement details block 1SP.
3. Implement order item component 2SP.
4. Implement order items list component 1SP.
5. Implement page component 1SP.
6. Unit tests 3SP.
7. Documentation 1SP.

Additionally we need to integrate this page with our application, but we can not do this right now because of the issue I described above. This task require additional effort and we can not measure the effort now.

@ericerway, also we have several questions for you:
1. **Do we need to implement only for guest user role? In case we need to support authorized user role as well this will highly affect estimates.**
1. Please, provide detailed description of 'Buy again' button behavior.
2. Please, provide detailed description of 'Share' button behavior.

**Comment by Starotitorov** [comment]
@ericerway, thank you for the response! So, what should happen when user clicks share button?

**Comment by ericerway** [comment]
For MVP it should link to a Product Details page for the item itself. Nothing complex.

**Comment by Starotitorov** [comment]
Frontend tasks:
- [ ] Implement common button group component.
- [ ] Implement details block.
- [ ] Implement order item component.
- [ ] Implement order items list component.
- [ ] Implement page component.
- [ ] Unit tests.
- [ ] Documentation.

**Comment by AlexeyKaryka** [comment]
@soumya-ashok Could you please take a look at comments I've left at invision?

**Comment by soumya-ashok** [comment]
@AlexeyKaryka I apologize for the delay in responding to this issue, but I left responses to your Invision comments a couple of days ago. Please let me know if you want to discuss further.

**Comment by ericerway** [comment]
Moving to Sprint 30 for review while fetch endpoints are explored.

**Comment by awilcoxa** [comment]
moving to backlog for additional grooming, there are graphql dependencies that must be accounted for.

**Comment by ericerway** [comment]
Moving back to Grooming for reconsideration; we have commits #526 and #762 to work from with the new GraphQL coverage. /CC @tjwiebell

**Comment by awilcoxa** [comment]
Closing as obsolete, new cart/checkout experience accounts for new order summary.
