### ISSUE TITLE
EPIC: Accessibility improvements for Venia (Lighthouse)

### ISSUE THREAD

**Issue by ericerway** [magento/pwa-studio#636]
From pwa-studio created by [ericerway](https://github.com/ericerway) : magento-research/pwa-studio#594  

## This issue is for the following packages:

[X] `venia-concept`
[ ] `pwa-buildpack`
[X] `peregrine`
[ ] `pwa-devdocs`
[ ] `upward-js`
[ ] `upward-spec`

## This issue is a:

[ ] Bug
[X] Feature suggestion
[ ] Documentation issue
[ ] Other (Please Specify)

### Environment

| Question                    |    Answer     |
| --------------------------- | :-----------: |
| Magento version             |  |
| Operating System + version  |  |
| node.js version (`node -v`) |  |
| npm version (`npm -v`)      |  |

## Description

As a shopper, I want to experience a fully accessible Venia storefront regardless of my abilities so that I can achieve WCAG 2.0 recommendations and Google Lighthouse recommendations.

https://www.w3.org/WAI/standards-guidelines/wcag/

## Expected result:

Updates to elements, colors, and language on key Venia experiences to improve accessibility as defined Google Lighthouse.

![image.png](https://images.zenhubusercontent.com/5a71f21a4b5806bc2bc51012/cdeea5a5-1adf-4099-8188-581547e6c1a2)

Categories: (affected)
- Elements Have Discernible Names
- Color Contrast is Satisfactory
- Page Specifies Valid Language

Pages: (affected)
- Homepage
- Category
- Product Details

## Tasks
- [ ] Update Venia home, category, and PD pages with recommended fixes from Lighthouse
- [ ] Review Google Lighthouse scores for Accessibility to verify (Lighthouse 4.0.0-alpha.1)
- [ ] Update documentation (as appropriate)

## Possible solutions:

Updates to Venia and UI components (peregrine) as appropriate.

**Comment by dmtrkad** [comment]
@ericerway , Are there any PBIs in "Ready for development" status that could be picked by us into this epic?

**Comment by ericerway** [comment]
Not yet, we have determined that this needs to be further groomed and associated with the core Peregrine (components) work first.

**Comment by ericerway** [comment]
@awilcoxa do we need both epics for accessibility or can we consolidate? (reference: #623)

**Comment by awilcoxa** [comment]
closing as duplicate
